name: ULDGN
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.8.30=py39h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.10=py39h5eee18b_0
  - mkl_random=1.2.7=py39h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.13.1=py39_cu117
  - torchtriton=3.0.0=py39
  - torchvision=0.14.1=py39_cu117
  - typing_extensions=4.11.0=py39h06a4308_0
  - urllib3=2.2.2=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - addict==2.4.0
      - apscheduler==3.11.0
      - astor==0.8.1
      - asttokens==2.4.1
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - conda-pack==0.8.0
      - contourpy==1.3.0
      - cupy-cuda110==8.5.0
      - cupy-cuda11x==13.3.0
      - cycler==0.12.1
      - cython==3.1.4
      - decorator==5.1.1
      - deepdiff==8.6.1
      - defusedxml==0.7.1
      - distlib==0.3.8
      - docopt==0.6.2
      - efficientnet-pytorch==0.7.1
      - mamba-ssm==1.2.0
      - einops==0.8.0
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fastrlock==0.8.2
      - filelock==3.11.0
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - gudhi==3.11.0
      - h5py==3.11.0
      - huggingface-hub==0.24.7
      - imageio==2.26.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jedi==0.19.1
      - joblib==1.4.2
      - json-tricks==3.17.3
      - jsondiff==2.2.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.7
      - longport==3.0.14
      - mamba-ssm==1.2.0
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mmcv==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ninja==1.11.1.1
      - nni==3.0
      - numpy==1.26.4
      - nvidia-ml-py==12.560.30
      - opencv-python==4.10.0.84
      - orderly-set==5.5.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.3.3
      - pot==0.9.5
      - prettytable==3.11.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.1
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pythonwebhdfs==0.2.3
      - pytz==2024.2
      - pywavelets==1.6.0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - randaugment==1.0.2
      - referencing==0.35.1
      - regex==2024.9.11
      - responses==0.25.3
      - rpds-py==0.20.0
      - safetensors==0.4.5
      - schedule==1.2.2
      - schema==0.7.7
      - scikit-learn==1.4.1.post1
      - scipy==1.13.1
      - seaborn==0.13.2
      - setuptools==74.1.2
      - shutup==0.2.0
      - simplejson==3.19.3
      - six==1.16.0
      - soupsieve==2.6
      - spectral==0.23.1
      - stack-data==0.6.3
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torchinfo==1.8.0
      - torchsummary==1.5.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.44.2
      - triton==2.2.0
      - typeguard==4.1.2
      - tzdata==2024.1
      - tzlocal==5.3.1
      - utils==1.0.2
      - virtualenv==20.26.6
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websockets==13.0.1
      - yapf==0.40.2
      - yarg==0.1.9
      - zipp==3.20.2
